name: 'Cache and install dependencies'
description: 'Caching dependencies and installing it'
inputs:
  is-caching:
    description: 'Should caching be turned on'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
  - name: Cache dependencies
    if: inputs.is-caching == 'true'
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true' || inputs.is-caching == 'true'
    run: npm ci
    shell: bash